source = $HOME/.cache/wal/colors-hyprlock.conf

background {
    monitor =
    path = $HOME/.cache/current_wallpaper.jpg    
    blur_passes = 3
    blur_size = 5
    noise = 0.0
    contrast = 1.0
    brightness = 0.8
    vibrancy = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2

    outer_color = $foreground
    inner_color = $background_50
    font_color = $color1

    fade_on_empty = false
    placeholder_text =

    dots_spacing = 0.2
    dots_center = true

    position = 0, 0
    halign = center
    valign = center

    rounding = 12
}

general {
    hide_cursor = true
    hide_cursor_timeout = 3
}
