source = $HOME/.cache/wal/colors-hyprlock.conf

background {
    monitor =
    path = $HOME/.cache/current_wallpaper.jpg    
    blur_passes = 3
    blur_size = 5
    noise = 0.0
    contrast = 1.0
    brightness = 0.8
    vibrancy = 0.0
}

# Date-Month
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %B")"
    color = $foreground
    font_size = 120
    font_family = JetBrains Mono
    position = 0, 400
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = $foreground
    font_size = 40
    font_family = JetBrains Mono
    position = 0, 240
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2

    outer_color = $foreground
    inner_color = $background_50
    font_color = $color1

    fade_on_empty = false
    placeholder_text =

    dots_spacing = 0.2
    dots_center = true

    position = 0, 0
    halign = center
    valign = center

    rounding = 12
}

# Reboot
label {
    monitor =
    text =  
    color = $foreground
    font_size = 60
    onclick = reboot now
    position = 0, 100
    halign = center
    valign = bottom
}

# Power off
label {
    monitor =
    text =  󰐥
    color = $foreground
    font_size = 60
    onclick = shutdown now
    position = 820, 100
    halign =left
    valign = bottom
}

# Suspend
label {
    monitor =
    text =  󰤄
    color = $foreground
    font_size = 60
    onclick = systemctl suspend
    position = -820, 100
    halign = right
    valign = bottom
}

general {
    hide_cursor = false
    hide_cursor_timeout = 3
}
