require("hyprland/animations")
require("hyprland/variables")
require("hyprland/general")
require("hyprland/layout")
require("hyprland/binds")
require("hyprland/execs")
require("hyprland/rules")
require("hyprland/env")
